### ISSUE TITLE
BedTool.window_maker() fails if genome not provided

### ISSUE THREAD

**Issue by andrewparkermorgan** [daler/pybedtools#101]
Attempting to run `BedTool.window_maker()` with interval instead of genome input fails as shown below.

```
Traceback (most recent call last):
  File "./tile_with_probes.py", line 36, in <module>
    kmers = regions.window_maker(w = args.kmer, s = args.step)
  File "/nas02/home/a/p/apm/lib/python2.7/site-packages/pybedtools-0.6.2-py2.7-linux-x86_64.egg/pybedtools/bedtool.py", line 623, in decorated
    result = method(self, *args, **kwargs)
  File "/nas02/home/a/p/apm/lib/python2.7/site-packages/pybedtools-0.6.2-py2.7-linux-x86_64.egg/pybedtools/bedtool.py", line 176, in wrapped
    kwargs = self.check_genome(**kwargs)
  File "/nas02/home/a/p/apm/lib/python2.7/site-packages/pybedtools-0.6.2-py2.7-linux-x86_64.egg/pybedtools/bedtool.py", line 1178, in check_genome
    raise ValueError('No genome specified. Use the "g" or '
ValueError: No genome specified. Use the "g" or "genome" kwargs, or use the .set_chromsizes() method
```

It looks to me like the contents of the BedTool are not being passed to `_wraps()` via the `implicit` argument.  If I make the following change at line 1911 in `bedtool.py` then `window_maker()` now runs as expected.

```
## OLD:
# @_wraps(prog='windowMaker', uses_genome=True, genome_none_if=['b'])
## NEW:
@_wraps(prog='windowMaker', implicit='b', uses_genome=True, genome_none_if=['b'])
```

But I have not checked whether or not this causes the function to break under other input cases.

**Comment by leeleavitt** [comment]
Would appreciate some updated documentation on this function.
