### ISSUE TITLE
Syntax Error upon installation

### ISSUE THREAD

**Issue by mpschr** [daler/pybedtools#140]
There is a problem with the installation script (see below).

My setup:
 - Ubuntu 12.04
 - Python 3.4.3 |Anaconda 2.2.0 (64-bit)|
 - Cython version 0.23
 - bedtools v2.24.0

```
pip install pybedtools
Collecting pybedtools
  Using cached pybedtools-0.6.9.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-b13zk05t/pybedtools/setup.py", line 1, in <module>
        import ez_setup
      File "/tmp/pip-build-b13zk05t/pybedtools/ez_setup.py", line 106
        except pkg_resources.VersionConflict, e:
                                            ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
```

**Comment by daler** [comment]
The master branch isn't released yet for Python 3. This will be updated soon, but in the meantime please use `conda install` using my channel:

`conda install -c daler pybedtools`

**Comment by mpschr** [comment]
Great - this worked!
