### ISSUE TITLE
BedTool function fails to parse floats

### ISSUE THREAD

**Issue by Adamtaranto** [daler/pybedtools#150]
Filtering intervals on float() value in 4th position. Was working fine untill recent pybedtools update. Now freaks out about floats.

```python
intervalList = [('chrm_01', 10, 20, 0.711),('chrm_01', 15, 30, 0.66),('chrm_01', 40, 60, 0.011),('chrm_01', 50, 80, 0.81221)]

pybedtools.BedTool(intervalList)
```

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/pybedtools/bedtool.py", line 502, in __init__
    fn = BedTool(iter(fn)).saveas().fn
  File "/usr/local/lib/python2.7/site-packages/pybedtools/bedtool.py", line 775, in decorated
    result = method(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pybedtools/bedtool.py", line 2889, in saveas
    compressed=compressed)
  File "/usr/local/lib/python2.7/site-packages/pybedtools/bedtool.py", line 1215, in _collapse
    for i in iterable:
  File "pybedtools/cbedtools.pyx", line 772, in pybedtools.cbedtools.IntervalIterator.__next__ (pybedtools/cbedtools.cxx:10427)
  File "pybedtools/cbedtools.pyx", line 649, in pybedtools.cbedtools.create_interval_from_list (pybedtools/cbedtools.cxx:8789)
  File "pybedtools/cbedtools.pyx", line 30, in pybedtools.cbedtools._cppstr (pybedtools/cbedtools.cxx:1679)
  File "pybedtools/stringsource", line 15, in string.from_py.__pyx_convert_string_from_py_std__in_string (pybedtools/cbedtools.cxx:12529)
TypeError: expected string or Unicode object, float found

**Comment by daler** [comment]
Hi - 
While it's different from the previous version, I think that the current behavior is actually the correct behavior.

The reason is that `Interval` objects store everything as strings with the exception of start and stop coords. It's trivial for pybedtools to convert the float to string when creating an `Interval` object out of the tuple. But when accessing that data it would be a string. That is,
```python
# hypothetical: convert float to string upon Interval creation
x = Interval("chr1", 10, 100, 5.0)
x[4]
# returns string "5.0", not 5.0
```
That implicit conversion could be surprising for users. It's more explicit for the caller to do the string conversion. That is, change your example to this:

```python
intervalList = [('chrm_01', 10, 20, '0.711'),('chrm_01', 15, 30, '0.66'),('chrm_01', 40, 60, '0.011'),('chrm_01', 50, 80, '0.81221')]
pybedtools.BedTool(intervalList)
```
