### ISSUE TITLE
random_subset of bam files - error

### ISSUE THREAD

**Issue by adomingues** [daler/pybedtools#177]
I was trying to do calculate coverage of 5's from random subsets of reads when I stumbled upon `random_subset`. There however some issues when applying it to largish files.

It works with the example bam:

``` python
a = pybedtools.example_bedtool('gdc.bam')
b = a.random_subset(2)
print(b)
```

> None    16      chr2L   71      255     5M      \*       0       0       TTCTC   IIIII   NM:i:0  NH:i:1
> None    16      chr2L   141     255     5M      \*       0       0       CACCA   IIIII   NM:i:0  NH:i:1

And it works with a very small bam file (~400 alignments):

``` python
insam = "Zili.bam"
reads = pybedtools.BedTool(insam)
b = reads.random_subset(2)
print(b)
```

> HWI-ST558:319:HJHNYADXX:1:1204:17267:77538      16      chr5    962056  255     28M     \*       0       0       CTCTTGGCTTAAATAGTCTGTGCTGTGT       JJIJJJJIJJJJJJJJJJIHHHHHFFFF    XA:i:0  MD:Z:28 RG:Z:1  NM:i:0
> HWI-ST558:319:HJHNYADXX:1:1208:4405:90382       16      chr5    962114  255     30M     \*       0       0       TTATTAATAATAACCCTCTGACCGTCATTT     IJIJIFIIIHGFACA:CCFEFHFFHHDEDD  XA:i:0  MD:Z:30 RG:Z:1  NM:i:0

But not on a large bam file (~15M reads):

``` python
insam = "adult.bam"
reads = pybedtools.BedTool(insam)
b = reads.random_subset(2)
```

This is the error I am getting:

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/fsimb/groups/imb-kettinggr/common_bin/env/local/lib/python2.7/site-packages/pybedtools/bedtool.py", line 775, in decorated
>     result = method(self, _args, *_kwargs)
>   File "/fsimb/groups/imb-kettinggr/common_bin/env/local/lib/python2.7/site-packages/pybedtools/bedtool.py", line 2929, in random_subset
>     idxs = list(range(len(self)))
>   File "/fsimb/groups/imb-kettinggr/common_bin/env/local/lib/python2.7/site-packages/pybedtools/bedtool.py", line 1077, in **len**
>     return self.count()
>   File "/fsimb/groups/imb-kettinggr/common_bin/env/local/lib/python2.7/site-packages/pybedtools/bedtool.py", line 2261, in count
>     return sum(1 for _ in iter(self))
>   File "/fsimb/groups/imb-kettinggr/common_bin/env/local/lib/python2.7/site-packages/pybedtools/bedtool.py", line 2261, in <genexpr>
>     return sum(1 for _ in iter(self))
>   File "/fsimb/groups/imb-kettinggr/common_bin/env/local/lib/python2.7/site-packages/pybedtools/bedtool.py", line 3322, in next
>     return self.**next**()
>   File "/fsimb/groups/imb-kettinggr/common_bin/env/local/lib/python2.7/site-packages/pybedtools/bedtool.py", line 3319, in **next**
>     return self._aligned_segment_to_interval(next(self.pysam_bamfile))
>   File "/fsimb/groups/imb-kettinggr/common_bin/env/local/lib/python2.7/site-packages/pybedtools/bedtool.py", line 3310, in _aligned_segment_to_interval
>     return create_interval_from_list(fields)
>   File "pybedtools/cbedtools.pyx", line 577, in pybedtools.cbedtools.create_interval_from_list (pybedtools/cbedtools.cxx:9893)
>   File "pybedtools/cbedtools.pyx", line 628, in pybedtools.cbedtools.create_interval_from_list (pybedtools/cbedtools.cxx:8988)
> OverflowError: can't convert negative value to CHRPOS

Also, it take several minutes (>10) before the error is thrown.

Other threads ([#122](https://github.com/daler/pybedtools/issues/122)) in here suggest that the _OverflowError_ is due to pysam and that it should have been fixed. Sadly I am stuck with python2.7 (bedtools v2.23.0).

Any idea on how to solve this? Do you know of other ways of randomly selecting SE reads from a bam in python?

Cheers

**Comment by adomingues** [comment]
Just to add that converting to bed first seems to work:

```python
sub = reads.bam_to_bed().random_subset(10)
print(sub)
```
> chr12   25142402        25142435        HWI-ST558:265:C49HNACXX:6:1116:6658:77434       0       +
> chr22   40795660        40795703        HWI-ST558:265:C49HNACXX:6:1116:17707:68634      255     -
> chr25   13415971        13415998        HWI-ST558:265:C49HNACXX:6:1309:16098:70866      0       -

Time to do the operations take a little hit for the conversion, but it works.
