### ISSUE TITLE
Not compiling in Python3.6

### ISSUE THREAD

**Issue by TarjinderSingh** [daler/pybedtools#206]
Just made a fresh install of Anaconda and it appears that `pybedtools` does not install with Python 3.6. Minor, but is there an easy way to fix this?

```
conda install pybedtools
Fetching package metadata .............
Solving package specifications: .
UnsatisfiableError: The following specifications were found to be in conflict:
  - pybedtools -> pysam >=0.8.1 -> python 2.7* -> openssl 1.0.1*
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by kyleabeauchamp** [comment]
Is this from bioconda?  Bioconda isn't yet supported on py36 right now, although work is ongoing.

**Comment by TarjinderSingh** [comment]
Yeah, it was from bioconda. I also tried pip but a similar error appeared..

**Comment by daler** [comment]
As Kyle mentioned, no py36 support yet in bioconda. But I don't see why it shouldn't work on py36 via pip. Can you provide the error you got when installing via pip?

**Comment by TarjinderSingh** [comment]
Hey! The error I get is:

```
  copying pybedtools/cbedtools.pxd -> build/lib.linux-x86_64-3.6/pybedtools
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-dowcab4k/pybedtools/setup.py", line 385, in <module>
        **setuptools_kwargs)
      File "/home/tsingh/conda/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/tsingh/conda/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/home/tsingh/conda/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/tsingh/conda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/command/install.py", line
 61, in run
      File "/home/tsingh/conda/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/home/tsingh/conda/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/tsingh/conda/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/tsingh/conda/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/home/tsingh/conda/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/tsingh/conda/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/tsingh/conda/lib/python3.6/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/tmp/pip-build-dowcab4k/pybedtools/setup.py", line 269, in build_extensions
        self.check_cython_extensions(self.extensions)
      File "/tmp/pip-build-dowcab4k/pybedtools/setup.py", line 266, in check_cython_extensions
        """ % src)
    Exception: Cython-generated file 'pybedtools/cbedtools.cxx' not found.
            Cython is required to compile pybedtools from a development branch.
            Please install Cython or download a source release of pybedtools.
    
    
    ----------------------------------------
Command "/home/tsingh/conda/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-dowcab4k/pybedtools/setu
p.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__
, 'exec'))" install --record /tmp/pip-yh0y958z-record/install-record.txt --single-version-externally-managed --compile" fai
led with error code 1 in /tmp/pip-build-dowcab4k/pybedtools/
```

**Comment by daler** [comment]
Can you first install Cython? `conda install cython` should do it.

**Comment by daler** [comment]
By the way, are you using `pip install pybedtools` or some other method? The [package on PyPI](https://pypi.python.org/packages/7c/66/8aecffd830eddbd05c1c3e737f87220cef9f2a8358f1d692f85b30269520/pybedtools-0.7.9.tar.gz#md5=498a9cf0bb6eaf1e6342463da2baa855) includes `pybedtools/cbedtools.cxx`.
