### ISSUE TITLE
non positional records error when intersecting bam with filtered vcf

### ISSUE THREAD

**Issue by mce1** [daler/pybedtools#212]
Dear Ryan,

first of all, thank you very much for the nice package! I've only started working with pybedtools and really like it a lot. However, I seem to be unable to get one (seemingly) simple task to work and was wondering if I could ask your help.

I would like to intersect a bam with a vcf that has been filtered first. (I have attached the two test files I use here: [test.vcf.gz](https://github.com/daler/pybedtools/files/981526/test.vcf.gz) and [test.bam.gz](https://github.com/daler/pybedtools/files/981528/test.bam.gz). Note, that I had to rename the bam to bam.gz so it would upload. Please remove the .gz upon downloading; it's just a normal bam.)

I can intersect the two original files without any problems:

```
>>> import pybedtools
>>> main_bam = pybedtools.BedTool('test.bam')
>>> main_vcf = pybedtools.BedTool('test.vcf.gz')
>>> main_bam.intersect(main_vcf).saveas().head()
21:25880549-26170654(-)_520_708_4:0:0_1:0:0_498	355	21	22582249	1	12M3468739N88M	=	26051077	3468928	AACTTGTCCAAGGTCTCAAAAGAAAAAGAAAAAGAAGAAATTAGAATAAATTGGACAGTCAATAAAGAGGCTAAAGGCATCTAGTCTTAATAATAAAGTT	2222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222	PG:Z:MarkDuplicates	RG:Z:test	NH:i:3	HI:i:3	nM:i:5	AS:i:177
 21:25880549-26170654(-)_520_708_4:0:0_1:0:0_498	355	21	22717328	1	12M3333660N88M	=	26051077	3333849	AACTTGTCCAAGGTCTCAAAAGAAAAAGAAAAAGAAGAAATTAGAATAAATTGGACAGTCAATAAAGAGGCTAAAGGCATCTAGTCTTAATAATAAAGTT	2222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222	PG:Z:MarkDuplicates	RG:Z:test	NH:i:3	HI:i:2	nM:i:5	AS:i:177
 21:25880549-26170654(-)_1001_1361_4:0:0_2:0:0_8da	419	21	24552455	3	11M1422746N17M725N72M	=	25997384	1447627	TTTTTTAGTGGAAACTGGGTTTCACCATTCACCTCATGAAAATTCCTCAAGTAGCCCAAGTGGACAGTTCTTAATACTACACTTTACTGGGGAAAGGAGC	2222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222	PG:Z:MarkDuplicates	RG:Z:test	NH:i:2	HI:i:2	nM:i:7	AS:i:175
 21:25880549-26170654(-)_819_1168_6:0:0_1:0:0_495	99	21	25102401	255	4S40M894919N56M	=	26021839	1283584	CCTTAAGCGCTGGGATTGCAAGCGTGAGCCACCACACCCAGCCTTTTCAATTAATGAAATATCAAATACTATATACTTCCCTCAAATATAGTGAGGTCAA	2222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222	PG:Z:MarkDuplicates	RG:Z:test	NH:i:1	HI:i:1	nM:i:9	AS:i:147
 21:25880549-26170654(-)_1649_1954_2:0:0_2:0:0_485	355	21	25119464	1	11M792266N89M	=	25911936	835199	CTATCAGCATTAAACACAAGTTTTGATAGTTTGTTTGTTTTCTAGCTCCTAGTGTTCAAAGAAATGTATATTGAAACACTATATGCATATAGCTAGCAAA	2222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222	PG:Z:MarkDuplicates	RG:Z:test	NH:i:3	HI:i:3	nM:i:3	AS:i:183
 21:25880549-26170654(-)_1649_1954_2:0:0_2:0:0_485	355	21	25219071	1	11M692659N89M	=	25911936	735592	CTATCAGCATTAAACACAAGTTTTGATAGTTTGTTTGTTTTCTAGCTCCTAGTGTTCAAAGAAATGTATATTGAAACACTATATGCATATAGCTAGCAAA	2222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222	PG:Z:MarkDuplicates	RG:Z:test	NH:i:3	HI:i:2	nM:i:3	AS:i:183
 21:25880549-26170654(-)_1509_1728_2:0:0_3:0:0_4ee	99	21	25272057	255	8M682526N92M	=	25955640	683683	CCCTGGGCCGTCTTTCTTGCATGGTATAAAGGTGAACGCATATAACCTGAGATCTGCTTGTTATTATTTTTCCATCAAAAGGAAAGGCACTCTGAAGGTG	2222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222	PG:Z:MarkDuplicates	RG:Z:test	NH:i:1	HI:i:1	nM:i:6	AS:i:183
 21:25880549-26170654(-)_1673_1954_1:0:0_4:1:0_6bd	355	21	25272442	1	11M639288N89M	=	25911912	1237045	CTAGCAGCATTAAACACAAGTTTTGATAGTTTGTTTCTTTTCAAGCTCCTAGTGTTCAAAGAAATGAATCTTGAAACACTATATGCATAAAGCTACCAAA	2222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222	PG:Z:MarkDuplicates	RG:Z:test	NH:i:4	HI:i:3	nM:i:5	AS:i:179
 21:25880549-26170654(-)_957_1256_5:0:0_4:0:0_37	355	21	25319485	1	14M662861N86M	=	26000026	680641	TTATGTATATTTAGTCAAGACGGGGTTTCATTCTGTTGGCCAGGTGGGTCTTGAACGCCTGACCTCAGGCATCCACCCACCTCAGCCTCCTAAAGCGCTG	2222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222	PG:Z:MarkDuplicates	RG:Z:test	NH:i:3	HI:i:3	nM:i:9	AS:i:177
 21:25880549-26170654(-)_641_913_3:0:0_1:0:1_489	419	21	25388007	3	13M633819N34M1I52M	=	26051000	663049	TTTTTCACAGTGAAATTTAAGTACAGCATTAATGACTGTGTAAAATTCAGCAATAATAACAGTTAATATTTGGAGCACACTTGTCAGGTGCAGACTTACA	2222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222	PG:Z:MarkDuplicates	RG:Z:test	NH:i:2	HI:i:2	nM:i:3	AS:i:132
```

Now, I try to filter the vcf first. 

```
>>> import re
>>> def filter_heterozygous_sites(feature):
...     ## works only for vcfs with one sample and GT as the only subfield in FORMAT
...     genotype = re.split('\||/', feature[-1])
...     if genotype[0] == genotype[1]:
...         return False
...     else:
...         return True
... 
>>> vcf_filtered = main_vcf.filter(filter_heterozygous_sites).saveas()
>>> vcf_filtered.head()
21	25882228	rs2829149	C	T	100	PASS	AA=C|||;AC=1;AF=0.622804;AFR_AF=0.5877;AMR_AF=0.5807;AN=2;DP=18465;EAS_AF=0.4454;EUR_AF=0.7545;NS=2504;SAS_AF=0.7474;VT=SNP	GT	0|1
 21	25882231	rs2211996	A	T	100	PASS	AA=T|||;AC=1;AF=0.888778;AFR_AF=0.7943;AMR_AF=0.8963;AN=2;DP=18623;EAS_AF=0.9841;EUR_AF=0.8837;NS=2504;SAS_AF=0.9182;VT=SNP	GT	0|1
 21	25882492	rs2408966	G	A	100	PASS	AA=G|||;AC=1;AF=0.775759;AFR_AF=0.5068;AMR_AF=0.8703;AN=2;DP=18919;EAS_AF=0.8482;EUR_AF=0.8767;NS=2504;SAS_AF=0.8937;VT=SNP	GT	0|1
 21	25883047	rs2252624	C	A	100	PASS	AA=A|||;AC=1;AF=0.804313;AFR_AF=0.6097;AMR_AF=0.8804;AN=2;DP=16094;EAS_AF=0.8482;EUR_AF=0.8767;NS=2504;SAS_AF=0.8937;VT=SNP	GT	0|1
 21	25883227	rs5843110	C	CT	100	PASS	AA=TT|T|TT|deletion;AC=1;AF=0.804313;AFR_AF=0.6097;AMR_AF=0.8804;AN=2;DP=15436;EAS_AF=0.8482;EUR_AF=0.8767;NS=2504;SAS_AF=0.8937;VT=INDEL	GT	0|1
 21	25883302	rs2408967	G	A	100	PASS	AA=G|||;AC=1;AF=0.801118;AFR_AF=0.5991;AMR_AF=0.8775;AN=2;DP=16605;EAS_AF=0.8482;EUR_AF=0.8767;NS=2504;SAS_AF=0.8937;VT=SNP	GT	0|1
 21	25884076	rs12481982	G	T	100	PASS	AA=G|||;AC=1;AF=0.774361;AFR_AF=0.5008;AMR_AF=0.8703;AN=2;DP=15668;EAS_AF=0.8482;EUR_AF=0.8777;NS=2504;SAS_AF=0.8937;VT=SNP	GT	0|1
 21	25884428	rs2186435	A	G	100	PASS	AA=G|||;AC=1;AF=0.866214;AFR_AF=0.708;AMR_AF=0.8948;AN=2;DP=16196;EAS_AF=0.9841;EUR_AF=0.8857;NS=2504;SAS_AF=0.9182;VT=SNP	GT	0|1
 21	25885149	rs5010535	T	G	100	PASS	AA=T|||;AC=1;AF=0.861821;AFR_AF=0.7057;AMR_AF=0.8847;AN=2;DP=15110;EAS_AF=0.9841;EUR_AF=0.8738;NS=2504;SAS_AF=0.9182;VT=SNP	GT	0|1
 21	25885829	rs2226442	T	C	100	PASS	AA=C|||;AC=1;AF=0.805112;AFR_AF=0.612;AMR_AF=0.8804;AN=2;DP=14355;EAS_AF=0.8482;EUR_AF=0.8777;NS=2504;SAS_AF=0.8937;VT=SNP	GT	0|1
```

So, filtering by itself works fine.

However, when I then try to intersect the bam with the filtered vcf I get the following error message:

```
>>> main_bam.intersect(vcf_filtered).saveas().head()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pybedtools/bedtool.py", line 778, in decorated
    result = method(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pybedtools/bedtool.py", line 337, in wrapped
    decode_output=decode_output,
  File "/usr/local/lib/python2.7/dist-packages/pybedtools/helpers.py", line 356, in call_bedtools
    raise BEDToolsError(subprocess.list2cmdline(cmds), stderr)
pybedtools.helpers.BEDToolsError: 
Command was:

	bedtools intersect -b /tmp/pybedtools.zARaqx.tmp -abam test.bam

Error message was:
ERROR: file /tmp/pybedtools.zARaqx.tmp has non positional records, which are only valid for the groupBy tool.

Tool:    bedtools intersect (aka intersectBed)
Version: v2.26.0
Summary: Report overlaps between two feature files.

...
```

I have also tried some other filters e.g.

```
>>> def filter_by_start(feature, start):
...     if feature.start == start:
...         return True
...     return False
... 

```
all with the same error. So, I think the problem is not with my filter in particular but with the filtering step as such.

Would be great if you could have a look at this and give me some feedback.

Thanks a lot in advance,

Maik

**Comment by daler** [comment]
Thanks for reporting. The issue is that the VCF header is not being copied over to the output when iterating over a VCF, so BEDTools doesn't recognize it as a proper VCF file. Using `.each()`, `.filter()`, or even `BedTool(i for i in other_bedtool)` will all cause this since they are all generators of `Interval` objects. The same error occurs on the command line if you do:

```bash
bedtools intersect -a a.vcf -b b.bed > out.vcf
bedtools intersect -a out.vcf -b b.bed
```
`bedtools intersect` has the `-header` option, so this should work as expected:
```bash
bedtools intersect -a out.vcf -b b.bed -header
```
In pybedtools it would be `out.intersect(b, header=True)`.

I'm actually not sure if there's a good solution for iterating over headers here in pybedtools. A generator of Interval files should not yield non-Interval things like header lines. Actually the same kind of problem happens on the command line if you use grep/awk without doing checks for `#` at the beginning of lines.

I think your best bet for VCF filtering will be using PyVCF/CyVCF/pysam. Then once it's filtered (with an intact header), use it with pybedtools.

**Comment by mce1** [comment]
Thanks a lot for the immediate reply!

**Comment by mce1** [comment]
Dear Ryan,

thanks a lot for your answer again. I have done as you suggested (loading the vcf-file as a PyVCF object, performing the filtering step with PyVCF methods, writing an intermediate file to disk, loading this intermediate file as bedtools object and then performing the bedtools manipulations) which works fine.

While writing intermediate files always seems a practical way for this type of operation, I was wondering if and how objects from these different packages (i.e. pybedtools, pysam, PyVCF) could be used directly by one of the other packages, especially for bam files. 

Under changes in v0.7.0 you say:

"... Instead, pysam is used for handling BAM files.

... pysam.AlignedSegment objects are currently converted to pybedtools.Interval objects when iterating over a BAM file. 

... for now you can use the pybedtools.BAM.pysam_bamfile attribute to access the underlying pysam.AlignmentFile."

I have tried the latter with the test file above:

```
>>> import pysam
>>> import pybedtools
>>> bamfile = pybedtools.BedTool('test.bam')
>>> pysam_bam = bamfile.pysam_bamfile
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'BedTool' object has no attribute 'pysam_bamfile'

```

I can open the file as a pysam.AlignmentFile first and then create a bedtools object from this, however, this object then cannot be parsed properly:

```
>>> pysam_bam = pysam.AlignmentFile('test.bam', 'rb')
>>> bedtool_bamfile = pybedtools.BedTool(pysam_bam)
>>> for line in bedtool_bamfile:
...     print line
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pybedtools/cbedtools.pyx", line 783, in pybedtools.cbedtools.IntervalIterator.__next__ (pybedtools/cbedtools.cxx:11107)
TypeError: 'pysam.libcalignedsegment.AlignedSegment' object is not iterable
```
 

I was wondering if you could maybe point me to an example of how to use of these options properly.

Thanks a lot again,

Maik

**Comment by daler** [comment]
I'll have to clarify the docs and release notes. It's the `BedTool`'s iterator that wraps `pysam.AlignmentFile`, not the `BedTool` itself. Below is how to use it.

I suppose I could open a pysam.AlignmentFile automatically upon instantiating a BedTool object and expose that via pysam_bamfile, but I'd prefer not to since that would likely leave open filehandles laying around. This way, a filehandle is only opened when you're iterating over it.

```python
import pybedtools

# x is a BedTool object, independent of file type
x = pybedtools.example_bedtool('x.bam')

for i in x:
    # For consistency, when iterating over x, we get Intervals --
    # same as any other file type
    break

# But underneath, it's iterating over a pysam.AlignmentFile
# and converting to Interval objects. If we want that AlignmentFile directly,
# we need to convert it to an iterator first
y = iter(x)

# y is now a pybedtools.bedtool.BAM object
y.pysam_bamfile
```
