### ISSUE TITLE
test_randomstats is failing on Debian

### ISSUE THREAD

**Issue by mr-c** [daler/pybedtools#241]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=892644 
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/build/1st/python-pybedtools-0.7.10/.pybuild/pythonX.Y_3.6/build/pybedtools/test/test1.py", line 796, in test_randomstats
    assert results['percentile'] == 89.5
AssertionError
```

**Comment by daler** [comment]
Thanks for reporting. This behavior depends on the version of BEDTools installed and I've reported upstream to https://github.com/arq5x/bedtools2/issues/607. I can fix pybedtools to match what BEDTools is reporting in v2.27 (might break again in the future), or possibly skip these tests. From the Debian packaging side do you have a preference?
