### ISSUE TITLE
FileNotFoundError is not defined (python 2.7) 

### ISSUE THREAD

**Issue by LiubovCh** [daler/pybedtools#248]
Hi,
While trying to reproduce the build with python 2.7 under Debian, I get this error:
```
======================================================================
ERROR: pybedtools.test.test1.test_issue_178
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/<<PKGBUILDDIR>>/.pybuild/cpython2_2.7_pybedtools/build/pybedtools/test/test1.py", line 2126, in test_issue_178
    except FileNotFoundError:
NameError: global name 'FileNotFoundError' is not defined

----------------------------------------------------------------------
```
As I do not have **bedGraphToBigWig**, I hit this `FileNotFoundError` exception, which is not defined in python 2.7. Defining it as `OSError` could possibly be a solution.

**Comment by smoe** [comment]
Hi, many thanks for spotting that. bedGraphToBigWig comes from here: http://hgdownload.cse.ucsc.edu/admin/exe/ and is to my knowledge not yet available in Debian. Somewhat unfortunate is that this is only available as a "free for academia" license. If we now put it as a regular build dependency, then this puts pybedtools out of the main Debian distribution into the "contrib" distribution.
Is there a way to have the test with bedGraphToBigWig somehow done only when that binary is available? And, is it fair to say that bedGraphToBigWig binary is recommended to be installed but not ultimately required? This would allow pybedtools to remain in main.

**Comment by daler** [comment]
Thanks both.

I will change the test to be skipped if bedGraphToBigWig cannot be found. It is definitely not required, nor is the related bedToBigBed or bigBedToBed.

**Comment by smoe** [comment]
Excellent. Many thanks!
