### ISSUE TITLE
BedTool.genome_coverage unexpected crash

### ISSUE THREAD

**Issue by EReckase** [daler/pybedtools#256]
[foo.zip](https://github.com/daler/pybedtools/files/2380112/foo.zip)

```
>>> from pybedtools import BedTool
>>> a = BedTool('foo.bam')
>>> g = a.genome_coverage(dz=True)
>>> len(g)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/python-2.7.5/lib/python2.7/site-packages/pybedtools/bedtool.py", line 1108, in __len__
    return self.count()
  File "/opt/python-2.7.5/lib/python2.7/site-packages/pybedtools/bedtool.py", line 2369, in count
    return sum(1 for _ in iter(self))
  File "/opt/python-2.7.5/lib/python2.7/site-packages/pybedtools/bedtool.py", line 2369, in <genexpr>
    return sum(1 for _ in iter(self))
  File "pybedtools/cbedtools.pyx", line 787, in pybedtools.cbedtools.IntervalIterator.__next__ (pybedtools/cbedtools.cxx:11123)
  File "pybedtools/cbedtools.pyx", line 697, in pybedtools.cbedtools.create_interval_from_list (pybedtools/cbedtools.cxx:9938)
pybedtools.cbedtools.MalformedBedLineError: Start is greater than stop
```

Am I doing something wrong here? bedtools genomecov seems to work ok:
```
# bedtools genomecov -dz -ibam foo.bam
IGHV7-81*01	0	5
IGHV7-81*01	1	5
IGHV7-81*01	2	5
IGHV7-81*01	3	5
IGHV7-81*01	4	5
IGHV7-81*01	5	5
IGHV7-81*01	6	5
IGHV7-81*01	7	5
IGHV7-81*01	8	5
IGHV7-81*01	9	5
IGHV7-81*01	10	5
IGHV7-81*01	11	5
IGHV7-81*01	12	5
IGHV7-81*01	13	5
IGHV7-81*01	14	5
...
```

**Comment by EReckase** [comment]
Note that converting this BAM to a BED, and then running genome_coverage on the BED also crashes with the same message.

**Comment by EReckase** [comment]
How do we get results from the call to genomecov? Every way I could think of I couldn't access the lines.

**Comment by daler** [comment]
The filename is accessible from the `fn` attribute, so you can do

```python
for line in open(g.fn):
    # do something with line
```

or 

```python
import pandas
df = pandas.read_table(g.fn)
```
