### ISSUE TITLE
Test failures with bedtools 2.27.1

### ISSUE THREAD

**Issue by rekado** [daler/pybedtools#260]
I'm upgrading the pybedtools package in GNU Guix from 0.6.9 to 0.7.10 and I get a couple of test failures (16 failures, 3 errors due to disabled internet access).

Here's an example of some of the failures:

```
======================================================================
FAIL: pybedtools.test.test_iter.test_i_methods
merge, i=gzip ibam=False, {'s': True, 'c': [4, 5, 6], 'o': 'distinct'}
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/gnu/store/am211hm7jb2y0schyzz4bx68z1i19l0h-python-nose-1.3.7/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/guix-build-python-pybedtools-0.7.10.drv-0/pybedtools-0.7.10/pybedtools/test/test_iter.py", line 68, in run
    assert res == expected
AssertionError: 
-------------------- >> begin captured stdout << ---------------------
/tmp/guix-build-python-pybedtools-0.7.10.drv-0/pybedtools-0.7.10/pybedtools/test/tmp/pybedtools.9znzc0hx.tmp
Method call:
BedTool.merge(s=True, c=[4, 5, 6], o=distinct)
Got:
chr1	1	200	feature1,feature2	0	+
chr1	150	500	feature3	0	-
chr1	900	950	feature4	0	+

Expected:
chr1	1	200	+	feature1,feature2	0	+
chr1	150	500	-	feature3	0	-
chr1	900	950	+	feature4	0	+

Diff:
--- 
 +++ 
 @@ -1,3 +1,3 @@
 -chr1	1	200	feature1,feature2	0	+
 -chr1	150	500	feature3	0	-
 -chr1	900	950	feature4	0	+
 +chr1	1	200	+	feature1,feature2	0	+
 +chr1	150	500	-	feature3	0	-
 +chr1	900	950	+	feature4	0	+
 Showing special characters:
Got:
chr1\t1\t200\tfeature1,feature2\t0\t+\n
chr1\t150\t500\tfeature3\t0\t-\n
chr1\t900\t950\tfeature4\t0\t+\n

Expected:
chr1\t1\t200\t+\tfeature1,feature2\t0\t+\n
chr1\t150\t500\t-\tfeature3\t0\t-\n
chr1\t900\t950\t+\tfeature4\t0\t+\n

Diff:
--- 
 +++ 
 @@ -1,3 +1,3 @@
 -chr1\t1\t200\tfeature1,feature2\t0\t+\n
 -chr1\t150\t500\tfeature3\t0\t-\n
 -chr1\t900\t950\tfeature4\t0\t+\n
 +chr1\t1\t200\t+\tfeature1,feature2\t0\t+\n
 +chr1\t150\t500\t-\tfeature3\t0\t-\n
 +chr1\t900\t950\t+\tfeature4\t0\t+\n
 
--------------------- >> end captured stdout << ----------------------
>>  assert 'chr1\t1\t200\tfeature1,feature2\t0\t+\nchr1\t150\t500\tfeature3\t0\t-\nchr1\t900\t950\tfeature4\t0\t+\n' == 'chr1\t1\t200\t+\tfeature1,feature2\t0\t+\nchr1\t150\t500\t-\tfeature3\t0\t-\nchr1\t900\t950\t+\tfeature4\t0\t+\n'
```

Another one that happens a few times is that completely different regions are output:

```
======================================================================
FAIL: pybedtools.test.test_iter.test_i_methods
shuffle, i=gzip ibam=False, {'seed': 1, 'genome': 'hg19', 'chrom': True}
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/gnu/store/am211hm7jb2y0schyzz4bx68z1i19l0h-python-nose-1.3.7/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/guix-build-python-pybedtools-0.7.10.drv-0/pybedtools-0.7.10/pybedtools/test/test_iter.py", line 68, in run
    assert res == expected
AssertionError: 
-------------------- >> begin captured stdout << ---------------------
/tmp/guix-build-python-pybedtools-0.7.10.drv-0/pybedtools-0.7.10/pybedtools/test/tmp/pybedtools.gh5__1i7.tmp
Method call:
BedTool.shuffle(seed=1, genome=hg19, chrom=True)
Got:
chr1	46341498	46341597	feature1	0	+
chr1	45615582	45615682	feature2	0	+
chr1	102762672	102763022	feature3	0	-
chr1	17293432	17293482	feature4	0	+

Expected:
chr1	59535036	59535135	feature1	0	+
chr1	99179023	99179123	feature2	0	+
chr1	186189051	186189401	feature3	0	-
chr1	219133189	219133239	feature4	0	+

Diff:
--- 
 +++ 
 @@ -1,4 +1,4 @@
 -chr1	46341498	46341597	feature1	0	+
 -chr1	45615582	45615682	feature2	0	+
 -chr1	102762672	102763022	feature3	0	-
 -chr1	17293432	17293482	feature4	0	+
 +chr1	59535036	59535135	feature1	0	+
 +chr1	99179023	99179123	feature2	0	+
 +chr1	186189051	186189401	feature3	0	-
 +chr1	219133189	219133239	feature4	0	+
 Showing special characters:
Got:
chr1\t46341498\t46341597\tfeature1\t0\t+\n
chr1\t45615582\t45615682\tfeature2\t0\t+\n
chr1\t102762672\t102763022\tfeature3\t0\t-\n
chr1\t17293432\t17293482\tfeature4\t0\t+\n

Expected:
chr1\t59535036\t59535135\tfeature1\t0\t+\n
chr1\t99179023\t99179123\tfeature2\t0\t+\n
chr1\t186189051\t186189401\tfeature3\t0\t-\n
chr1\t219133189\t219133239\tfeature4\t0\t+\n

Diff:
--- 
 +++ 
 @@ -1,4 +1,4 @@
 -chr1\t46341498\t46341597\tfeature1\t0\t+\n
 -chr1\t45615582\t45615682\tfeature2\t0\t+\n
 -chr1\t102762672\t102763022\tfeature3\t0\t-\n
 -chr1\t17293432\t17293482\tfeature4\t0\t+\n
 +chr1\t59535036\t59535135\tfeature1\t0\t+\n
 +chr1\t99179023\t99179123\tfeature2\t0\t+\n
 +chr1\t186189051\t186189401\tfeature3\t0\t-\n
 +chr1\t219133189\t219133239\tfeature4\t0\t+\n
 
--------------------- >> end captured stdout << ----------------------
>>  assert 'chr1\t46341498\t46341597\tfeature1\t0\t+\nchr1\t45615582\t45615682\tfeature2\t0\t+\nchr1\t102762672\t102763022\tfeature3\t0\t-\nchr1\t17293432\t17293482\tfeature4\t0\t+\n' == 'chr1\t59535036\t59535135\tfeature1\t0\t+\nchr1\t99179023\t99179123\tfeature2\t0\t+\nchr1\t186189051\t186189401\tfeature3\t0\t-\nchr1\t219133189\t219133239\tfeature4\t0\t+\n'
```

**Comment by daler** [comment]
Adressed in #264.
