### ISSUE TITLE
Errors being thrown after python (3.9.1), pybedtools updates

### ISSUE THREAD

**Issue by mcnaircm** [daler/pybedtools#336]
Recently updated python versions and went through the process of updating pybedtools as well, and have been unable to run without issue ever since.  The most recent error I'm getting is shown below.  I've tried removing and re-installing pybedtools using pip, installing the development version via github, all with the same results.  Any help/suggestions would be much appreciated! 

/home/cmm024/.pyenv/versions/3.9.1/lib/python3.9/runpy.py:127: RuntimeWarning: 'pybedtools.__main__' found in sys.modules after import of package 'pybedtools', but prior to execution of 'pybedtools.__main__'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
Traceback (most recent call last):
  File "/home/cmm024/.pyenv/versions/3.9.1/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/cmm024/.pyenv/versions/3.9.1/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/cmm024/.pyenv/versions/3.9.1/lib/python3.9/site-packages/pybedtools/__main__.py", line 45, in <module>
    main()
  File "/home/cmm024/.pyenv/versions/3.9.1/lib/python3.9/site-packages/pybedtools/__main__.py", line 21, in main
    m = import_module("pybedtools.scripts")
  File "/home/cmm024/.pyenv/versions/3.9.1/lib/python3.9/site-packages/pybedtools/__main__.py", line 12, in import_module
    __import__("%s" % (name,), globals(), locals(), [], -1)
ValueError: level must be >= 0

**Comment by daler** [comment]
Thanks for reporting. While I don't fully understand the issue, this is happening in the `main.py` module which is for the scripts, which haven't seemed to get much usage. In the latest release v0.8.2 they have been removed from being installed in the package, though the files are still available.

Can you give the latest v0.8.2 a try?

**Comment by daler** [comment]
Closing since I haven't heard of any other issues related to this, but please reopen if it's still a problem!
