### ISSUE TITLE
Error When Running Shuffle

### ISSUE THREAD

**Issue by Jome0169** [daler/pybedtools#344]
Hello, 

Hope you're doing well. I receive the following error when I attempt to use `shuffle` with the `exl` regions flag. The error is as follows: 

```
Things to check:
Traceback (most recent call last):
  File "/home/jpm73279/.conda/envs/pybed_only/lib/python3.9/site-packages/pybedtools/helpers.py", line 391, in call_bedtools
    p = subprocess.Popen(
  File "/home/jpm73279/.conda/envs/pybed_only/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/jpm73279/.conda/envs/pybed_only/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 7] Argument list too long: 'bedtools'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/jpm73279/13.ACR_CNS_analysis/01.analysis/permutation_test_CNS_scACRs/gen_permutation_class.py", line 130, in <module>
    shuffled_regions = generate_shuffled_features(bed_file_removed_scores,
  File "/scratch/jpm73279/13.ACR_CNS_analysis/01.analysis/permutation_test_CNS_scACRs/gen_permutation_class.py", line 56, in generate_shuffled_features
    shuffled_features = new_bed.shuffle(g = genome_file, excl = excl_regions,
  File "/home/jpm73279/.conda/envs/pybed_only/lib/python3.9/site-packages/pybedtools/bedtool.py", line 917, in decorated
    result = method(self, *args, **kwargs)
  File "/home/jpm73279/.conda/envs/pybed_only/lib/python3.9/site-packages/pybedtools/bedtool.py", line 396, in wrapped
    stream = call_bedtools(
  File "/home/jpm73279/.conda/envs/pybed_only/lib/python3.9/site-packages/pybedtools/helpers.py", line 489, in call_bedtools
    print("\n\t" + "\n\t".join(problems[err.errno]))
KeyError: 7
(pybed_only)

```

Any thoughts what could be causing this? I attempted to truncate both my input as well as the exclusion regions to only chrom, start, and stop features but this also didn't work.

**Comment by Jome0169** [comment]
Solved - Instead of the exl tag pointing to a `pybedtool` it needs to point to a saved bed file. So just save your pybedtool as pybedtool.saveas("x.bed") and pass this to the excl flag.

Hope this helps someone.
